### ISSUE TITLE
Multiple exif:tag write errors

### ISSUE THREAD

**Issue by fierceX** [TechnikTobi/little_exif#10]
I tried multiple tags such as FNumber, ShutterSpeedValue, ApertureValue, etc., and they don't report an error when written, but the result is wrong. When reading via the exiftool tool, there is an alert message:
```
Warning                         : Bad offset for ExifIFD FNumber
```
Reading with this library will report an error:
```
……little_exif-0.3.3/src/metadata.rs:504:40:
range end index 38 out of range for slice of length 35
```

**Comment by TechnikTobi** [comment]
Hi, could you please provide an example (with an image!) where this happens so that I can reproduce this?

**Comment by fierceX** [comment]
This problem occurs in the default example. I set the above-mentioned field values after reading, and an error will be reported when reading again.

For example:
```
metadata.set_tag(
		ExifTag::FNumber(vec![20])
	);
```

**Comment by fierceX** [comment]
@TechnikTobi  hi，Am I using it the wrong way?

**Comment by TechnikTobi** [comment]
No, you are using it correctly. However, this issue hasn't anything to do with multiple writes. For example, the following also fails in a similar fashion:

```
let mut metadata = Metadata::new();

metadata.set_tag(
    ExifTag::FNumber(vec![2024])                  // FAILS
    // ExifTag::RecommendedExposureIndex(vec![2024]) // works
);

metadata.write_to_file(Path::new("./rsrc/copy.jpg"));

for tag in Metadata::new_from_path(jpg_path).unwrap().data()
{
    println!("{:?}", tag);
}
```

What I can tell from this right now is that something goes wrong during the encoding process when writing tags that fulfill the following:

- Belong to ExifIFD (and not IFD0)
- Have an offset value to the actual data in their data field (as Components * Byte/Component > 4 Bytes)

Both properties are fulfilled by the `FNumber ` tag, but not e.g. by `RecommendedExposureIndex` (Components * Byte/Component <= 4 Bytes) or ImageDescription (IFD0).

**Comment by TechnikTobi** [comment]
Update: So I found the problem. In short, the issue has to do with the RATIONAL64U/S data type. Right now, as in your example with the `FNumber` tag, you need to provide a Vec<u32>, which only somewhat makes sense. However, what is actually required by the standard are two 4 byte integers for representing floats in a nominator/denominator fashion. I'm working on the code for this translation right now, you can expect a fix for this in the upcoming days.

**Comment by fierceX** [comment]
@TechnikTobi Thanks, maybe not only FNumber, I found that ApertureValue, ShutterSpeedValue, etc. seem to have the wrong data type as well.

**Comment by TechnikTobi** [comment]
Fixed it. For `RATIONAL64U` (and `RATIONAL64S`) tags like e.g. `FNumber` you can now set the value like this:

```
metadata.set_tag(
    ExifTag::FNumber(vec![1.4.into()])
)
```
