### ISSUE TITLE
Could not get IFD0 tags!

### ISSUE THREAD

**Issue by mschnell1** [TechnikTobi/little_exif#11]
I do see e.g. comments inserted in a jpg file by the Windows 10+ explorer,but when trying to examine a file from a digital camera I get no fields but an error` Could not get IFD0 tags! ` (no panic). 

I also tried the "revolt" fork with the same result.

Can this be improved ?

**Comment by TechnikTobi** [comment]
Hi, could you please provide an example image file so that I can reproduce this?

**Comment by mschnell1** [comment]
-> https://www.bitvibe.de/Upload/A0579575.jpg

**Comment by TechnikTobi** [comment]
Thanks! Short update: The reason why this fails is that two EXIF tags are written using the wrong format (`ExifImageWidth` and `ExifImageHeight` should be INT32U but are written as INT16U). I'll work on a way for trying to convert values to the right format in such cases. You may expect an update with this feature in the upcoming days.

**Comment by mschnell1** [comment]
Great !
Thanks !

**Comment by TechnikTobi** [comment]
Please check if version 0.4.1 resolves this issue.

**Comment by mschnell1** [comment]
Thanks a lot for the very fast update !

Seems to work now with an image from a -> Make("FUJIFILM") Model("X-T5")
trying more pictures later today ....

does not work with an image from a "Xiaomi" "2312DRAABG" (whatever this is....)
Error messages: 
Could not get IFD0 tags:
 Could not decode SubIFD:
  Illegal format for known tag! Tag: ExifVersion([]) Expected: UNDEF Got: STRING

I'll upload that file later today....

**Comment by mschnell1** [comment]
In the debugger at  `metadata.rs` line` 550` I see:
`i` = 0, `encoded data` = 0, 0x15, 1, 0,    0, 4, 0, 0,   0, 4,  0x0f,     0xa0, 1, 1, 0, 4, ....
maybe this helps....

**Comment by mschnell1** [comment]
a rust program I did With another jpg file I see 
```
Tiff 270
**** id ImageDescription = Thumbs Annotation 
```
with a rust program I did with the `kamadak-exif` crate, but `little_exif` does not show the description when doing 
```
            for field in meta.data().iter() {
                match field {
                    ExifTag::ImageDescription(s) => {
                        println!("ImageDescription  : {}", s);
                    }
```
but does count 40 fields.

**Comment by mschnell1** [comment]
now I used the example code from crates.io to write an inage description to this file. 
```
    let mut metadata = Metadata::new();
    metadata.set_tag(ExifTag::ImageDescription("Hello World!".to_string()));
    let res = metadata.write_to_file(std::path::Path::new(&file_path));
    println!("x1: {:?}", res);
```
This does work without an error.

But then trying to read that file again with the "little" code that worked before gets the error message:
```
thread 'main' panicked at C:\Users\mschnell\.cargo\registry\src\index.crates.io-6f17d22bba15001f\little_exif-0.4.1\src\metadata.rs:461:70:
range end index 2 out of range for slice of length 0
```

**Comment by mschnell1** [comment]
The not working picture is here -> https://bitvibe.de/Upload/IMG_20240828_184255.jpg

**Comment by TechnikTobi** [comment]
I referenced the different comments in their respective new issue just so that things don't get mixed up/confused.
