### ISSUE TITLE
custom tags

### ISSUE THREAD

**Issue by mschnell1** [TechnikTobi/little_exif#16]
The "little" doc say: `Currently supports only ... a few dozen tags in IFD0 and ExifIFD`.
It would be nice if - when a certain `feature ` is set - the user could provide a file with additional tags.
(I am not experienced enough with Rust Macro programming to know it such is even possible.)

**Comment by TechnikTobi** [comment]
As of now, basically all trivial IFD0 and ExifIFD tags should be implemented. Other tags will likely require more advanced handling than simply providing additional tags to the macro in some way.

If you could be more specific regarding the tags you need I can take a look into them.

**Comment by mschnell1** [comment]
Right now I am happy with the tags provided by `little_exif` out of the box. 
I just wanted to share this thought ....

**Comment by TechnikTobi** [comment]
Alright! If you encounter a tag that hasn't been implemented yet just let me know. There are plans to further extend capabilities in that direction (and fix tags that aren't fully supported yet due to their complexity, e.g. ThumbnailOffset), but that just is not a top priority at the moment.
