### ISSUE TITLE
Implementing TIFF

### ISSUE THREAD

**Issue by TechnikTobi** [TechnikTobi/little_exif#17]
> This has to do with the MakerNotes IFD and, as I recently found out, is also the cause for issue #6. For now, with the fix in 0.5.0-beta2, this data will be handled as a single tag and not further processed. Please let me know if this solves the issue for you as well on other photos.

Yea ! The set of files I am currently testing with allows reading with `new_from,_path`. 
Many files also are handled without an error by `new_from_vec`.
but in the set also  is a file with the extension `.tif`. `FileExtension::from_str`cant handle this as there is no "tif" arm in the `FileExtension` enum yet. 
I did not yet test writing a file.....

_Originally posted by @mschnell1 in https://github.com/TechnikTobi/little_exif/issues/2#issuecomment-2395611381_

**Comment by mschnell1** [comment]
looking forward to testing...

**Comment by TechnikTobi** [comment]
Available now in 0.6.0-beta6!

**Comment by TechnikTobi** [comment]
Seems like this worked on the first try?

**Comment by mschnell1** [comment]
Just running a bunch of jpg file to check for glitches. 
I'll to a test with some TIFs ASAP.

**Comment by mschnell1** [comment]
This file
www.bitvibe.de/Upload/A0040275_5.tif
does
```
thread 'main' panicked at C:\Users\Michael Schnell\.cargo\registry\src\index.crates.io-6f17d22bba15001f\little_exif-0.6.0-beta.6\src\ifd\mod.rs:705:29:
attempt to subtract with overflow
```

**Comment by TechnikTobi** [comment]
With what code?
