### ISSUE TITLE
Very long time until "No EXIF data found!" is returned.

### ISSUE THREAD

**Issue by TechnikTobi** [TechnikTobi/little_exif#21]
With this file it seems to take a very long time until  the error "No EXIF data found!" is returned.

www.bitvibe.de/Upload/A0462208sw.JPG

Another image: 

www.bitvibe.de/Upload/A0386910sw.JPG

_Originally posted by @mschnell1 in https://github.com/TechnikTobi/little_exif/issues/2#issuecomment-2396938290_

**Comment by mschnell1** [comment]
Those are the only black and white picture files I tested.

All others are color and none takes long to issue a result (Ok or Error)

**Comment by TechnikTobi** [comment]
Solved via `std::io::BufReader` - available in release 0.5.1

**Comment by mschnell1** [comment]
Testing ....

**Comment by mschnell1** [comment]
With 0.5.1 no panic any more. 
But still 12 of the 100 files under test get `No Exif found`.
Doing spme more research...

**Comment by mschnell1** [comment]
One of the files is

www.bitvibe.de/Upload/A0386910sw.JPG (already known) 

another is 

www.bitvibe.de/Upload/A0234657.JPG

**Comment by TechnikTobi** [comment]
Both images don't contain any EXIF data

**Comment by mschnell1** [comment]
moreover there is one file (in another testing set) which provides:
```
Could not get IFD0 tags:
 Could not decode SubIFD:
  Illegal format for known tag! Tag: ExposureCompensation([]) Expected: RATIONAL64S Got: RATIONAL64U
WARNING: Can't read metadata - Create new & empty struct
```
www.bitvibde.de/Upload/dsc22921.jpg

**Comment by mschnell1** [comment]
> Both images don't contain any EXIF data

I'll have another look ASAP.

**Comment by mschnell1** [comment]
I found that the files that don't have exif information seem top be decently handles and jet just the ImageDescription Tag. Unfortunately ThumbsPlus does not see same, but Explorer does.
The message printed by the galley is not necessary in the released version, as the caller can see the fact that the exif infprmation is new by data.len() = 0
