### ISSUE TITLE
hangs

### ISSUE THREAD

**Issue by mschnell1** [TechnikTobi/little_exif#27]
Just to let you know: EẀith this file the analyzing hangs seemingly forever.

-> www.bitvibe.de/Upload/_DSCZ784Z.JPG

**Comment by TechnikTobi** [comment]
Can't reproduce the issue using 

```
	let jpg_path = Path::new("./rsrc/_DSCZ784Z.JPG");

	// Read metadata from file
	for tag in Metadata::new_from_path(jpg_path).unwrap().data()
	{
		println!("{:?}", tag);
	}
````

**Comment by mschnell1** [comment]
Opening (AFAIR both from file as from Vec).

**Comment by TechnikTobi** [comment]
Well, I can't reproduce this issue so I can't tell what is going on.

**Comment by TechnikTobi** [comment]
Is this still the case with the newest beta version?

**Comment by mschnell1** [comment]
No 
this file now sais: `Error: failed to fill whole buffer`
(which I believe I did not see with beta.4 in the 1000 other testing files.

**Comment by mschnell1** [comment]
This now seems to result in aborting the executable.

**Comment by mschnell1** [comment]
Supposedly this is OK, as that file was written  by a still buggy version of little_exif.

**Comment by TechnikTobi** [comment]
> Supposedly this is OK, as that file was written by a still buggy version of little_exif. 

That would explain a lot, as the given file misses the expected JPG end of image segment 0xFFD9. 

> My original file for that image works fine with beta.4.

In that case I assume it also works with beta 5? If so we can close this issue.

**Comment by mschnell1** [comment]
Yep I meant Beta.5
Lets close this.
