### ISSUE TITLE
v0.6.0-beta.1 does not recognize Exif in even more file

### ISSUE THREAD

**Issue by mschnell1** [TechnikTobi/little_exif#32]
I get e.g. this messages by Little_Exif:

Error during decoding: Custom { kind: Other, error: "No EXIF data found!" }

I did provide several files that showed that behavior

But with Beta.1 it seems than many more files are affected.

**Comment by TechnikTobi** [comment]
Do you have an example where 0.5.1 recognizes EXIF data but 0.6.0-beta1 doesn't?

**Comment by mschnell1** [comment]
OK....
... searching...

**Comment by mschnell1** [comment]
Here you are...
www.bitvibe.de/Upload/ds218351.jpg

**Comment by mschnell1** [comment]
Exactly: 
 - reading the file by
```
        let mut file_content = fs::read(&source_file_path).context(source_token.source.clone())?;
        let mut metadata = Metadata::new_from_vec(&file_content, file_extension)?;
```
modifying `ImageDescription` by
```
        metadata.set_tag(ExifTag::ImageDescription(source_token.token.clone()));
        metadata.write_to_vec(&mut file_content, file_extension)?;
```
write file by
```
        fs::write(target_p, file_content)?;
```

**Comment by mschnell1** [comment]
unfortunately I need to do 
```
 let file_extension = get_file_type(&source_file_path).unwrap();
```
twice, as it can't be passed by reference. 
Does this might introduce a problem ?

**Comment by TechnikTobi** [comment]
I have a new suspicion. This 

> ThumbsPlus even does not recognize the oientation and shows the picture 90° turned. Picture and Exif Is correctly shown 

sounds like that the metadata (not just EXIF but all of the IFD stuff) has been corrupted in a way that ThumbsPlus is unable to read it, as this also includes things like the orientation. This can be caused by little_exif in case some tags require special care (e.g. they have additional offset data that doesn't get processed yet). 

Going through the tags in your example file I found 0x0201 and 0x0202 - tags that are related to thumbnail image data, with 0x0201 being the offset to the thumbnail. Now, if the EXIF data gets changed in length (very likely in case of updating the image description), the offset to the thumbnail needs to be updated as well, which I haven't accounted for previously. 

The new 0.6.0-beta2 should fix this. Please let me know if this has any effect on your example image and the way it's oriented in ThumbsPlus.

**Comment by TechnikTobi** [comment]
> The "assertion" panic I described before does not happen any more ! Great.

Good to hear.

> I understand that this mainly happens when LittExif claims it does not understand the Exif information and goes e.g.:

> Error during decoding: Custom { kind: Other, error: "No EXIF data found!" }
WARNING: Can't read metadata - Create new & empty struct

Do you have an example where 0.5.1 is able to detect the Exif information and 0.6.0-beta.2 can't? 

> But e.g. ds218351 which did keep the original EXIF tags and is decoded correctly by Thumbsplus after being written by 0.5.1, is not decoded by ThumbsPlus and shown side-wise after being written by 6.0-beta.2, even if little_exif does not complain and the other Exif tags seem to be in place.

So, just to clarify: The result of processing ds218351 with 0.5.1 is perfectly fine (upright), but using 0.6.0-beta.1 or .2 produces an image that ThumbsPlus displays sideways? Strange.

Based on another idea (that is related to the order of writing IFDs to the file) I updated the encoder again in 0.6.0-beta.3. If this has any effect on picture orientation please let me know. 

Also, what version of ThumbsPlus are you using? Then I can try to install that locally for these testing purposes.

**Comment by mschnell1** [comment]
> 
> Do you have an example where 0.5.1 is able to detect the Exif information and 0.6.0-beta.2 can't?
> 
I believe I have many. I'll do a search ASAP.

> So, just to clarify: The result of processing ds218351 with 0.5.1 is perfectly fine (upright), but using 0.6.0-beta.1 or .2 produces an image that ThumbsPlus displays sideways? Strange.

Yep

I'll upload the results...


> 
> Also, what version of ThumbsPlus are you using? Then I can try to install that locally for these testing purposes.

Unfortunately the company "Cerious" does not exist any more. 
I suppose I have an installation file...

AFAIR, same provides a 30 day trial.

**Comment by mschnell1** [comment]
www.bitvibe.de/Upload/8890_ds218351_beta.jpg
www.bitvibe.de/Upload/8890_ds218351.jpg

**Comment by mschnell1** [comment]
> Do you have an example where 0.5.1 is able to detect the Exif information and 0.6.0-beta.2 can't?
Sorry that seems to be a wrong inpression of mine.

**Comment by TechnikTobi** [comment]
> > Do you have an example where 0.5.1 is able to detect the Exif information and 0.6.0-beta.2 can't?
> 
> I believe I have many. I'll do a search ASAP.
> 
> Sorry that seems to be a wrong impression of mine.

Ok, then I'll assume that 0.5.1 and 0.6.0 detect the same Exif information for now until a counter-example comes up.

> > So, just to clarify: The result of processing ds218351 with 0.5.1 is perfectly fine (upright), but using 0.6.0-beta.1 or .2 produces an image that ThumbsPlus displays sideways? Strange.
> 
> Yep
> 
> I'll upload the results...

Okay, and what about beta3? The uploaded image seems to be the result of beta1 or beta2. 

> > Also, what version of ThumbsPlus are you using? Then I can try to install that locally for these testing purposes.
> 
> Unfortunately the company "Cerious" does not exist any more. I suppose I have an installation file...

Let that be my problem. Just want to know if it's version 7, 8, 10, ...?

**Comment by mschnell1** [comment]
I'll try Beta 3 ASAP (some hours...)
I'm using Tnumbs Plus v 10. supposedly the latest that had been released.

**Comment by mschnell1** [comment]
Suggestion for a possible cause of problems (e.g with thumbsPlus) : 
 - The Exif data contain a th8mbnail
 - the `ImageDescription `of the original file contains one or more  newline ("\n") characters.

**Comment by TechnikTobi** [comment]
> Suggestion for a possible cause of problems (e.g with thumbsPlus) :
> 
> * The Exif data contain a thumbnail and hence is huge
> * the `ImageDescription `of the original file contains one or more  newline ("\n") characters.

How did you come up with these two suggestions? Are they based on your collection of images and how "working" images differ from "non-working" ones? 

Something you could try for both of these cases (assuming you haven't tried this already) is to simply read in the exif information from a file and immediately writing it back to the file without changing e.g. the ImageDescription.

**Comment by mschnell1** [comment]
With Beta.3 no Error Message by Little_Exif with 
[www.bitvibe.de/Upload/2017_aachen_abendhimmel_emilio.jpg](http://www.bitvibe.de/Upload/2017_aachen_abendhimmel_emilio.jpg)

**Comment by mschnell1** [comment]
> How did you come up with these two suggestions? Are they based on your collection of images and how "working" images differ from "non-working" ones?

Not really, there are some 100 from some 1000 that don't "work".   The ones that do and that I did check seem to have the said properties.

> 
> Something you could try for both of these cases (assuming you haven't tried this already) is to simply read in the exif information from a file and immediately writing it back to the file without changing e.g. the ImageDescription.

I'll try to find out ASAP....

**Comment by mschnell1** [comment]
WOW !!!!!
With Beta.3 no obvious problems regarding ThumbsPlus any more. It always sees the ÌmageDescription` written by GREAT_Exif. 

I'll check if the files Litte_Exif refuses to decode really don't feature EXIF information ASAP ....

**Comment by mschnell1** [comment]
One weird thing: 
some pictures get an `ImageDescription`as three exclamation marks.
Is this a kind of debug leftover ?

**Comment by mschnell1** [comment]
I tested that several files reporting `Error during decoding: Custom { kind: Other, error: "No EXIF data found!" }` do feature exif information, at least ThumbsPlu8s reports a `comment`

moreover I get 
`Error during decoding: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }`

and a huge lot if times:
`Illegal endian information!` (new with beta.3 ? ) 

also: 
```
Could not decode SubIFD GPS:
  Illegal format for known tag! Tag: GPSAltitudeRef("") Expected: STRING Got: INT8U
```

**Comment by mschnell1** [comment]
Should I do dedicated issues for these  - even if it's a Beta right now ? 
Let me know fro which issue you need more examples.

**Comment by TechnikTobi** [comment]
> With Beta.3 no obvious problems regarding ThumbsPlus any more.

That is great to hear :-)

> Should I do dedicated issues for these - even if it's a Beta right now ?
Let me know fro which issue you need more examples.

I'll create issues based on your comments with what information is required for further investigation.
