### ISSUE TITLE
Unexpected exclamation marks

### ISSUE THREAD

**Issue by TechnikTobi** [TechnikTobi/little_exif#34]
> One weird thing: 
> some pictures (supposedly all from the same original source/Camera) show a `Comment` (AKA "Annotation") as `three exclamation marks `in ThumbsPlus. Explorer Details shows the correct 'Image Description` as `title`(and no exclamation marks whatsoever. 
> 
> In the file there indeed is a "!!!" string somewhere.
> The original file does not contain such a string. 
> 
> I did check my software but did not find any hint of three exclamation marks.
> 
_Originally posted by @mschnell1 in https://github.com/TechnikTobi/little_exif/issues/32#issuecomment-2438276239_

Required:
- Example file where this comes up
- The string you are trying to write as ImageDescription, i.e. what you expected to read but get "!!!" instead

**Comment by mschnell1** [comment]
www.bitvibe.de/Upload/A0040453.JPG
setting `ImageDescription` to "IW Collection, Fotoshooting, Rheinberg, Juni 2008"
which actually does works, according to Explorer Details `Titel`.

**Comment by TechnikTobi** [comment]
Can you tell me what you get now for Titel and comment with this [modified file](https://drive.google.com/file/d/1xQXgVqMyAA9MellK6YX2PFH0P9j1k7Hz/view?usp=share_link)?

**Comment by mschnell1** [comment]
I get 
"l_e"

?!?!?!?

**Comment by TechnikTobi** [comment]
That is what I was hoping for ;-) This means that the "!!!" string comes from the Photoshop Segment (see issue #35) that already exists in your source JPG image file (note: this segment is specific to JPG only). I used a hex editor to locate the exclamation marks and changed them so something I came up with ("l_e" as abbreviation for "little_exif"). 

This means however that adding the ImageDescription via little_exif won't work. As I am not an expert in the Photoshop Segment data structure and edit the description there as well we could think about simply removing the segment (as it does not hold any data that obviously seems important:

<img width="1193" alt="Bildschirmfoto 2024-10-26 um 13 08 59" src="https://github.com/user-attachments/assets/4543dcd4-3753-47f8-974c-7aa98cfba8ee">

The highlighted area is this Photoshop Segment (as noted by the 0xFFED that are located right before the area). The next two bytes tell us that this segment has a length of 0x002C bytes, then comes some Photoshop Version information (I guess?) with the String that shows up as Comment/Titel at the end (here "l_e", the original file shows the three exclamation marks). 

Removing this segment does not show any immediate drawbacks for now, and I could add a routine that does exactly that for JPG files.

**Comment by mschnell1** [comment]
Hmm.
How can I force that the `ImageDescription` Exif takes priority over the PhotoShop stuff ?

>My proposal: Removing this segment does not show any immediate drawbacks for now, and I could add a routine that does exactly that for JPG files.

Yep an option in Little-Exif to kill the Photoshop section would be great.

**Comment by TechnikTobi** [comment]
Functions for clearing the APP12 and APP13 segment (both are related to Photoshop, see [here](https://github.com/corkami/formats/blob/master/image/jpeg.md#jpeg-1997)) are now available in 0.6.0-beta4 and can be used via:

```
Metadata::clear_app13_segment(&mut file_content, file_extension)?;
```

**Comment by mschnell1** [comment]
I added this line after reading the file content. #
Unfortunately nor ThumbsPlus does not accept many files to be pictures any more.

**Comment by TechnikTobi** [comment]
Was this already the case with [my two example images](https://github.com/TechnikTobi/little_exif/issues/35#issuecomment-2439490566)?

**Comment by mschnell1** [comment]
No. Your test images shows just fine, only with weird the "comments" we discussed.

Here tje orihinalk of an example with the new issue:

www.bitvibe.de/Upload(dsc61076.jpg

**Comment by TechnikTobi** [comment]
And what if you only perform the APP13 segment removal without modifying the metadata (i.e. disabling `metadata.write_to_vec...`)?

**Comment by mschnell1** [comment]
Same: no picture recognized.

**Comment by TechnikTobi** [comment]
I see, I am able to reproduce this at least.

**Comment by mschnell1** [comment]
[A0040453.JPG](http://www.bitvibe.de/Upload/A0040453.JPG) does work OK.

**Comment by TechnikTobi** [comment]
Found, fixed and released in beta5

**Comment by mschnell1** [comment]
I don't see any problem with Beta.5 here !
Thanks a lot for making this happen !!!
