### ISSUE TITLE
"No EXIF data found!" with 0.6.0-beta3

### ISSUE THREAD

**Issue by TechnikTobi** [TechnikTobi/little_exif#35]
> I tested that several files reporting `Error during decoding: Custom { kind: Other, error: "No EXIF data found!" }` do feature exif information, at least ThumbsPlus reports a `comment` and Explorer Details a `Titel`

_Originally posted by @mschnell1 in https://github.com/TechnikTobi/little_exif/issues/32#issuecomment-2438852691_

Required:
- Example image file that produces the above little_exif error but has a Titel in Explorer & comment in ThumbsPlus. 

Note: Both the Titel and comment don't necessarily imply the existence of Exif information as they could also be caused by XMP data, so don't be disappointed if there actually isn't any Exif in there

**Comment by mschnell1** [comment]
Hmmm. 
most files do have camera data. I suppose those do count as exif ? 
I'll try to find an example....

**Comment by mschnell1** [comment]
I tested some but could not yet find any with camera data.
So maybe this in fact is a no-issue.

**Comment by TechnikTobi** [comment]
Yes, looking at the file there is only a Photoshop Image Resource Marker Segment that contains "Bella Rose, CHIO Aachen, Juli 2019 (Foto: Stefan Lafrentz)" that causes the Comment/Titel, which was likely added by exporting the image from Photoshop. No Exif information in there, sorry :-/ 

However, when I add an ImageDescription using little_exif the macOS image viewer displays the added `ImageDescription` - is this not the case for Explorer/ThumbsPlus? If so, we could think about removing the Photoshop Segment. I modified your example file:

- Simply setting the ImageDescription tag on an empty metadata struct and writing that: [AddedImageDescription](https://drive.google.com/file/d/1erAYfDAI4M5mdgxwMysPJQOfyCwOC-yX/view?usp=share_link)
- Taking the image with added ImageDescription and manually removing the Photoshop Segment: [AddedImageDescriptionNoPhotoshopSegment](https://drive.google.com/file/d/1B8bdvx_yZRdMKUfz1kFIPlwrjbrWLZKK/view?usp=share_link)

Let me know what works for you

**Comment by mschnell1** [comment]
With my project, I have no problems regarding this issue. I only need the resulting files to be in good condition and feature the `ImageDescription` I have  Great_Exif update for me. 

I just wanted to report this in case you might want to know about. 

Thanks a lot !

regarding me, we can close this issue.
