### ISSUE TITLE
Unexpected EOF error

### ISSUE THREAD

**Issue by TechnikTobi** [TechnikTobi/little_exif#36]
> moreover with some files, I get 
> `Error during decoding: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }`

_Originally posted by @mschnell1 in https://github.com/TechnikTobi/little_exif/issues/32#issuecomment-2438852691_

Required:
- Example file that produces the above error

**Comment by mschnell1** [comment]
www.bitvibe.de/Upload/IMG-20180904-WA0002.jpg

**Comment by TechnikTobi** [comment]
Problem found and fixed. Will be available in the next beta.

**Comment by mschnell1** [comment]
Great !
