### ISSUE TITLE
SubIFD GPS Decode Error: Unexpected format for GPSAltitudeRef

### ISSUE THREAD

**Issue by TechnikTobi** [TechnikTobi/little_exif#38]
> also with some files: 
> ```
> Could not decode SubIFD GPS:
>  Illegal format for known tag! Tag: GPSAltitudeRef("") Expected: STRING Got: INT8U
> ```

_Originally posted by @mschnell1 in https://github.com/TechnikTobi/little_exif/issues/32#issuecomment-2438852691_

Required:
- Example file that causes the above error

**Comment by mschnell1** [comment]
www.bitvibe.de/Upload/2017_stuttgart_07_.jpeg

**Comment by TechnikTobi** [comment]
Fix will be available in the next beta
