### ISSUE TITLE
Panic while reading images

### ISSUE THREAD

**Issue by Linken-code** [TechnikTobi/little_exif#6]
When I was reading the photo, the Metadata:: new_from_path method panicked

```
    match Metadata::new_from_path(&image_path) {
        Ok(metadata) => {
            println!("metadata--{:#?}", metadata.data());
        }
        Err(err) => {
            println!("err ---{:#?}", err);
        }
    }
```
![1709373625094](https://github.com/TechnikTobi/little_exif/assets/71937862/89ed041e-a0ea-4aaf-9156-fd12f230d302)

The photo used for testing is this one

![test](https://github.com/TechnikTobi/little_exif/assets/71937862/9420afb8-2a57-4bae-a188-a719f6d62b1f)

**Comment by TechnikTobi** [comment]
Solved as of release 0.5.1
